name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ./ETS2ATS.ModlistManager.csproj

      - name: Build
        run: dotnet build ./ETS2ATS.ModlistManager.csproj -c Release --no-restore

      - name: Publish (portable)
        run: dotnet publish ./ETS2ATS.ModlistManager.csproj -c Release -r win-x64 --self-contained false -o publish/win-x64

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: modlist-manager-win-x64
            path: publish/win-x64
            if-no-files-found: error

  codeql:
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
